# Generated by Django 3.0.4 on 2020-06-02 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20200520_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyBug',
            new_name='MyBag',
        ),
    ]
