# Generated by Django 3.0.4 on 2020-06-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20200602_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='info',
            field=models.CharField(default='Info about Item', max_length=100000),
        ),
    ]
