# Generated by Django 3.0.4 on 2020-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_category_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='quanity',
            field=models.FloatField(default=0),
        ),
    ]
